#pragma once
enum class STATE
{
	LOGIN_CONNECT_SUCCESS,
	CS_LOGIN_REQ_LOGIN_SENT,
	LOGIN_TRY_DISCONNECT, // 다운클라와 정상을 구분하기 위해 사용

	CHAT_CONNECT_TRY,

	CHAT_CONNECT_SUCCESS,
	CS_CHAT_REQ_LOGIN_SENT,

	CS_CHAT_RES_LOGIN_RECV,
	CS_CHAT_RES_SECTOR_MOVE_RECV,
	CS_CHAT_RES_MESSAGE_RECV,

	CS_CHAT_REQ_SECTOR_MOVE_SENT,
	CS_CHAT_REQ_MESSAGE_SENT,
	CS_CHAT_REQ_HEARTBEAT_SENT,
	CHAT_TRY_DISCONNECT, // 다운클라와 정상을 구분하기 위해 사용
};
